# This yaml file is for loading local database, server port, disable eureka and set jwt-rest-service endpoint
SERVER_PORT: 8088

POSTGRES_USERNAME: test
POSTGRES_PASSWORD: test
POSTGRES_DBNAME: organization
POSTGRES_SERVICE: localhost:5432
DB_SSLMODE: disable

EUREKA_HOST: localhost:8761
EUREKA_USER: test
EUREKA_PASSWORD: test

ISSUER_ADDRESS: http://api-gateway:9001

ISSUER_URI: ${ISSUER_ADDRESS}/issuer
OAUTH_CLIENTS: oauth-client
#JWT_SET_URI: ${ISSUER_ADDRESS}/issuer/.well-known/jwks.json

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@${EUREKA_HOST}/eureka