server:
  port: ${SERVER_PORT}

logging:
  level:
    root: error
    me.sonam.organization: info
    org.springframework.web: info
    org.springframework.security: info
    org.springframework.security.oauth2: info
    org.springframework.boot.autoconfigure: warn

spring:
  application:
    name: organization-rest-service
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_SERVICE}/${POSTGRES_DBNAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    properties:
      sslMode: ${DB_SSLMODE}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}

permitpath:
  - path: /organizations/api/health/*
    httpMethods: GET